-- DWH.VC._AUTO_BACKUP_CONTROL definition
create or replace TABLE _AUTO_BACKUP_CONTROL (
	OBJECT_TYPE VARCHAR(255) NOT NULL,
	SCHEMA VARCHAR(25) NOT NULL,
	OBJECT_NAME VARCHAR(255) NOT NULL,
	AUTOBACKUP_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	LAST_COMMIT_ID NUMBER(38,0),
	LAST_COMMIT_TS TIMESTAMP_NTZ(9),
	LAST_COMMIT_COMMENT VARCHAR(16777216),
	LAST_COMMIT_USER VARCHAR(16777216),
	primary key (OBJECT_TYPE, SCHEMA, OBJECT_NAME)
);



