CREATE OR REPLACE FUNCTION VC."UDF_MAX_COMMIT_ID"("OBJECT_TYPE1" VARCHAR(16777216), "SCHEMA_NAME" VARCHAR(16777216), "OBJECT_NAME1" VARCHAR(16777216))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS 'SELECT IFNULL((SELECT MAX(COMMIT_ID) FROM VC._OBJECT_DDL WHERE OBJECT_TYPE = OBJECT_TYPE1 AND SCHEMA= SCHEMA_NAME AND OBJECT_NAME=OBJECT_NAME1),0) as MAX_COMMIT_ID


';